# Generated by Django 5.1.3 on 2025-05-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='feedback',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='theme',
            new_name='subject',
        ),
    ]
